### ISSUE TITLE
Invalid CLZ macro in libxml2

### ISSUE THREAD

**Issue by ahomescu** [immunant/c2rust#1366]
Transpiling libxml2 creates an invalid `CLZ` macro that's a redefinition of the C-specific `__builtin_clzll`:
```rust
    #[c2rust::src_loc = "78:9"]
    pub const CLZ: unsafe extern "C" fn(std::ffi::c_ulonglong) -> std::ffi::c_int =
        unsafe { __builtin_clzll };
```

**Comment by fw-immunant** [comment]
Shouldn't this be failing in CI, since the testsuite includes libxml2? What commit does this occur with?

**Comment by ahomescu** [comment]
Reproduced on cbf4e0a20a54fcea886813e9f76394d049e7b75b, let me try current master.

**Comment by ahomescu** [comment]
Still happening on 973811e17d14cbb96cb84a6ff3298bc3171be240.

**Comment by ahomescu** [comment]
> Shouldn't this be failing in CI, since the testsuite includes libxml2? What commit does this occur with?

I'm seeing this on libxml2 which [seems to be disabled in CI](https://github.com/immunant/c2rust/blob/master/.github/workflows/internal-testsuite.yml#L132).

**Comment by kkysen** [comment]
I think this is happening because `__builtin_clzll` is an intrinsic that we normally translate as `.leading_zeros()`, but this isn't working when the function and the call are separated through a const macro.

**Comment by fw-immunant** [comment]
> I think this is happening because `__builtin_clzll` is an intrinsic that we normally translate as `.leading_zeros()`, but this isn't working when the function and the call are separated through a const macro.

Yeah, we correctly transpile calls of builtins but not taking their value.

**Comment by ahomescu** [comment]
I think this has been fixed, libxml2 seems to work fine.

**Comment by kkysen** [comment]
Oh I was leaving this open because the underlying issue isn't fixed yet.
