### ISSUE TITLE
my experience trying c2rust on openconnect

### ISSUE THREAD

**Issue by ctaggart** [immunant/c2rust#177]
I tried out c2rust on openconnect and the result can be seen in https://github.com/ctaggart/openconnect-rust. I committed the scripts that to the repository as well as the code. I started working through [a pull request](https://github.com/ctaggart/openconnect-rust/pull/2/files), but it is going to be too much work for something that seems automateable. Hopefully, I just have c2rust configured wrong.

I built and ran a debug version of c2rust on my MacBook with the latest macOS, rust, and master branches. I remember there was an error in release mode. I'll run again and post it here. I think c2rust is operating on individual source files and not the whole program. May be? The function imports are all off. I get the feeling that it should stick the external function definitions in modules per header and import those modules into code modules that nead them. In the current generated code, the same external functions are declared in each module.

For the external function that the app creates, it would be great to keep track of those and add module imports and using statements for the other modules that require the functions.

Anyhow, great work so far! Excited to see where this goes.

**Comment by ctaggart** [comment]
c2rust in release mode is erroring out. I think this may be the error:
```
Could not find CTypeId(3403) in TypedAstContext
```
but here is the [whole log](https://gist.github.com/ctaggart/c202407c344cafb870a68f6bd5fdca06) from `./run-c2rust.sh &> c2rust-openconnect.log` on my laptop.

**Comment by rinon** [comment]
The missing type is a bug in our handling of an OS X library. The missing type warnings above the error show where that's occurring. We'll look into that, should be a quick fix. I have no idea why debug and release would differ there, as they should identical.

As for imports, yes, c2rust acts just like a C compiler and operates on each translation unit (file) independently. Since there's nothing in C that actually matches declarations across translation units, that's actually a bit of a hard problem. We have experimental support for a transformation that attempts to reorganize all the declarations into proper Rust modules and add use statements as needed. Try adding `--reorganize-definitions` to your transpile command and see how that works for you. It doesn't work on all codebases yet, so ymmv.

**Comment by rinon** [comment]
It looks like the missing type is an Apple extension that we probably won't support (https://clang.llvm.org/docs/LanguageExtensions.html#blocks). Can you trying adding `-fno-blocks` to your compiler flags during transpiling? You can do this by adding `--` then `-fno-blocks` to the end of the `c2rust transpile` command. (I'd also recommend adding `-w` to silence warnings so your transpiler output is reasonable, btw).

**Comment by ctaggart** [comment]
Thank you @rinon. I made those [changes](https://github.com/ctaggart/openconnect-rust/commit/9df8421b760073e204c83d2b5ed8862f70a40425), set the [correct iframework path](https://github.com/ctaggart/openconnect-rust/commit/b2a7dd77e3b15b7229cf1870d84deed63d8d4684), and  now the error looks to be:

```
Transpiling cstp.c
[33mwarning:[0m Missing child 140214595267784 of node AstNode { tag: TagImplicitCastExpr, children: [Some(140214595267784)], loc: SrcSpan { fileid: 190, begin_line: 182, begin_column: 7, end_line: 182, end_column: 16 }, type_id: Some(140214601295488), rvalue: RValue, macro_expansions: [], extras: [String("BitCast")] }
Exported Clang AST was invalid. Check warnings above for unimplemented features.
[34m-->[0m /Users/cameron/github/openconnect/cstp.c:182:7
 [-Wclang-ast]
Transpiling auth.c
[33mwarning:[0m Missing child 140214621521920 of node AstNode { tag: TagImplicitCastExpr, children: [Some(140214621521920)], loc: SrcSpan { fileid: 136, begin_line: 732, begin_column: 17, end_line: 732, end_column: 26 }, type_id: Some(140214618332800), rvalue: RValue, macro_expansions: [], extras: [String("BitCast")] }
Exported Clang AST was invalid. Check warnings above for unimplemented features.
[34m-->[0m /Users/cameron/github/openconnect/auth.c:732:17
 [-Wclang-ast]
[33mwarning:[0m Missing child 140214621607080 of node AstNode { tag: TagImplicitCastExpr, children: [Some(140214621607080)], loc: SrcSpan { fileid: 136, begin_line: 1158, begin_column: 43, end_line: 1158, end_column: 52 }, type_id: Some(140214618332800), rvalue: RValue, macro_expansions: [], extras: [String("BitCast")] }
Exported Clang AST was invalid. Check warnings above for unimplemented features.
[34m-->[0m /Users/cameron/github/openconnect/auth.c:1158:43
 [-Wclang-ast]
thread 'main' panicked at 'not yet implemented: Attributed(CQualTypeId { qualifiers: Qualifiers { is_const: false, is_restrict: false, is_volatile: false }, ctype: CTypeId(268) }, Some(Nullable))', c2rust-transpile/src/translator/mod.rs:4597:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

The [full log](https://gist.github.com/ctaggart/c202407c344cafb870a68f6bd5fdca06) is much shorter now.

**Comment by rinon** [comment]
Could you run with the environment var `RUST_BACKTRACE=1` set? Would like to see a backtrace for this.

**Comment by ctaggart** [comment]
Sure thing.

```
Transpiling cstp.c
[33mwarning:[0m Missing child 140504598672584 of node AstNode { tag: TagImplicitCastExpr, children: [Some(140504598672584)], loc: SrcSpan { fileid: 190, begin_line: 182, begin_column: 7, end_line: 182, end_column: 16 }, type_id: Some(140504587346560), rvalue: RValue, macro_expansions: [], extras: [String("BitCast")] }
Exported Clang AST was invalid. Check warnings above for unimplemented features.
[34m-->[0m /Users/cameron/github/openconnect/cstp.c:182:7
 [-Wclang-ast]
Transpiling auth.c
[33mwarning:[0m Missing child 140504626316456 of node AstNode { tag: TagImplicitCastExpr, children: [Some(140504626316456)], loc: SrcSpan { fileid: 136, begin_line: 1158, begin_column: 43, end_line: 1158, end_column: 52 }, type_id: Some(140504662624896), rvalue: RValue, macro_expansions: [], extras: [String("BitCast")] }
Exported Clang AST was invalid. Check warnings above for unimplemented features.
[34m-->[0m /Users/cameron/github/openconnect/auth.c:1158:43
 [-Wclang-ast]
[33mwarning:[0m Missing child 140504626226176 of node AstNode { tag: TagImplicitCastExpr, children: [Some(140504626226176)], loc: SrcSpan { fileid: 136, begin_line: 732, begin_column: 17, end_line: 732, end_column: 26 }, type_id: Some(140504662624896), rvalue: RValue, macro_expansions: [], extras: [String("BitCast")] }
Exported Clang AST was invalid. Check warnings above for unimplemented features.
[34m-->[0m /Users/cameron/github/openconnect/auth.c:732:17
 [-Wclang-ast]
thread 'main' panicked at 'not yet implemented: Attributed(CQualTypeId { qualifiers: Qualifiers { is_const: false, is_restrict: false, is_volatile: false }, ctype: CTypeId(268) }, Some(Nullable))', c2rust-transpile/src/translator/mod.rs:4597:22
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: std::panicking::continue_panic_fmt
   7: std::panicking::begin_panic_fmt
   8: c2rust_transpile::translator::Translation::import_type
   9: c2rust_transpile::translator::Translation::convert_type
  10: c2rust_transpile::translator::structs::<impl c2rust_transpile::translator::Translation>::get_field_types
  11: c2rust_transpile::translator::structs::<impl c2rust_transpile::translator::Translation>::convert_struct_fields
  12: c2rust_transpile::translator::Translation::convert_decl
  13: c2rust_transpile::translator::translate::{{closure}}
  14: scoped_tls::ScopedKey<T>::set
  15: syntax::with_globals
  16: c2rust_transpile::translator::translate
  17: c2rust_transpile::transpile_single
  18: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  19: c2rust_transpile::transpile
  20: c2rust_transpile::main
  21: std::rt::lang_start::{{closure}}
  22: std::panicking::try::do_call
  23: __rust_maybe_catch_panic
  24: std::rt::lang_start_internal
  25: main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by rinon** [comment]
aa4bdf7f71750f3927a987178fdd2db018c5c498 should fix this, could you test?

**Comment by ctaggart** [comment]
It does! It now generated code. It still doesn't like because or errors linking to _openconnect functions. the manual way to fix it should be automateable by c2rust https://github.com/ctaggart/openconnect-rust/issues/1#issuecomment-544740797.

**Comment by ctaggart** [comment]
Closing this in favor of more focused issues.
